### ISSUE TITLE
Input component: Support for `datalist` Prop in Input Component

### ISSUE THREAD

**Issue by galiprandi** [galiprandi/react-tools#12]
#### Description
We propose adding a new feature to the Input component to support a `datalist` prop. This prop will accept an optional array of strings. If provided, the component will render a `datalist` element with each string as an `option`. Render inside a `label` and after the `input`. Additionally, the `id` prop will be required when the `datalist` prop is used to correctly associate the input element with the datalist.

#### Objectives
- Add a `datalist` prop to the Input component.
- Ensure the `id` prop is required when `datalist` is provided, and log an error to the console if it is missing.
- When the `datalist` prop is passed, render a `datalist` tag with one `option` for each string in the array.
- Ensure the component functions correctly without the `datalist` prop.
- Update documentation to reflect the new functionality and provide examples.

#### Example
```jsx
<Input
  id="example-input"
  label="Pick your option"
  datalist={['Option 1', 'Option 2', 'Option 3']}
/>
```
This will render:
```html
<label>
  Pick your option
  <input id="example-input" list="example-input-datalist" />
  <datalist id="example-input-datalist">
    <option value="Option 1"></option>
    <option value="Option 2"></option>
    <option value="Option 3"></option>
  </datalist>
</label>
```

#### Benefits
- Adds flexibility to the Input component by supporting native HTML5 datalist functionality.
- Enhances user experience by providing a list of predefined options.

#### Acceptance Criteria
- The `datalist` prop should be optional and accept an array of strings.
- The `id` prop should be required when the `datalist` prop is provided.
- When provided, a `datalist` element should be rendered with each string as an `option`.
- Update the component documentation with usage instructions and examples.

#### Notes
- No new tests are required for this feature.
- Ensure that the Input component remains functional when the `datalist` prop is not provided.

**Comment by nesyG** [comment]
Hello, I would like to help with this issue if it's available.

**Comment by galiprandi** [comment]
> Hello, I would like to help with this issue if it's available.

"Hello, the issue is still open, so your collaboration would be greatly appreciated."

**Comment by galiprandi** [comment]
Thanks, @nesyG, for your contribution to this great feature. 🦾

**Comment by galiprandi** [comment]
Thanks, @nesyG, for your contribution to this great feature. 🦾
